/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as WordmarkLabRouteImport } from './routes/wordmark-lab'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as ApiPublicPropertiesRouteImport } from './routes/api/public/properties'
import { Route as ApiPublicScansRouteImport } from './routes/api/public/scans'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const WordmarkLabRoute = WordmarkLabRouteImport.update({
  id: '/wordmark-lab',
  path: '/wordmark-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPropertiesRoute = ApiPublicPropertiesRouteImport.update({
  id: '/api/public/properties',
  path: '/api/public/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScansRoute = ApiPublicScansRouteImport.update({
  id: '/api/public/scans',
  path: '/api/public/scans',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/upload': typeof UploadRoute
  '/wordmark-lab': typeof WordmarkLabRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/api/public/properties': typeof ApiPublicPropertiesRoute
  '/api/public/scans': typeof ApiPublicScansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/upload': typeof UploadRoute
  '/wordmark-lab': typeof WordmarkLabRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/api/public/properties': typeof ApiPublicPropertiesRoute
  '/api/public/scans': typeof ApiPublicScansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/upload': typeof UploadRoute
  '/wordmark-lab': typeof WordmarkLabRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/api/public/properties': typeof ApiPublicPropertiesRoute
  '/api/public/scans': typeof ApiPublicScansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portfolio'
    | '/upload'
    | '/wordmark-lab'
    | '/rooms/$roomId'
    | '/api/public/properties'
    | '/api/public/scans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portfolio'
    | '/upload'
    | '/wordmark-lab'
    | '/rooms/$roomId'
    | '/api/public/properties'
    | '/api/public/scans'
  id:
    | '__root__'
    | '/'
    | '/portfolio'
    | '/upload'
    | '/wordmark-lab'
    | '/rooms/$roomId'
    | '/api/public/properties'
    | '/api/public/scans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortfolioRoute: typeof PortfolioRoute
  UploadRoute: typeof UploadRoute
  WordmarkLabRoute: typeof WordmarkLabRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  ApiPublicPropertiesRoute: typeof ApiPublicPropertiesRoute
  ApiPublicScansRoute: typeof ApiPublicScansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordmark-lab': {
      id: '/wordmark-lab'
      path: '/wordmark-lab'
      fullPath: '/wordmark-lab'
      preLoaderRoute: typeof WordmarkLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties': {
      id: '/api/public/properties'
      path: '/api/public/properties'
      fullPath: '/api/public/properties'
      preLoaderRoute: typeof ApiPublicPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scans': {
      id: '/api/public/scans'
      path: '/api/public/scans'
      fullPath: '/api/public/scans'
      preLoaderRoute: typeof ApiPublicScansRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortfolioRoute: PortfolioRoute,
  UploadRoute: UploadRoute,
  WordmarkLabRoute: WordmarkLabRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  ApiPublicPropertiesRoute: ApiPublicPropertiesRoute,
  ApiPublicScansRoute: ApiPublicScansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
